name: Android Builder

on:
    workflow_dispatch: 

jobs: 
    capBuild:
            name: Build Repo with capacitor 
            runs-on: ubuntu-latest
            steps:
                -   name: Checkout
                    uses: actions/checkout@v4
                -   name: show github.ref_type
                    run: | 
                            echo ${{ github.ref_name }}
                            echo ${{ github.ref_type }}
                            echo ${{ github }}
                -   name: Setup Node
                    uses: actions/setup-node@v1
                    with:
                        node-version: '20.x'
                -   name: Install
                    run: npm ci
                -   name: Build
                    run: npm run build
                -   name: Sync
                    run: npx cap sync android

                -   name: Setup JDK
                    uses: actions/setup-java@v4
                    with:
                        java-version: '21'
                        distribution: 'zulu'
                
                -   name: Make gradlew executable
                    run: chmod +x android/gradlew

                -   name: Build APK
                    run: cd android && ./gradlew assembleDebug

                -   name: Upload APK to artifacts
                    uses: actions/upload-artifact@v4
                    with:
                        name: todo.apk
                        path: android/app/build/outputs/apk/debug/app-debug.apk
                -   name: Upload to GitHub Release
                    uses: softprops/action-gh-release@v2
                    if: github.ref_type == 'tag'
                    with:
                        files: android/app/build/outputs/apk/release/app-release.apk
                        overwrite: true
                    env:
                        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                        
            
    