name: Android Builder

on:
    workflow_dispatch: 

jobs: 
    capBuild:
            name: Build Repo with capacitor 
            runs-on: ubuntu-latest
            steps:
                -   name: Checkout
                    uses: actions/checkout@v2
                -   name: Setup Node
                    uses: actions/setup-node@v1
                    with:
                        node-version: '12.x'
                -   name: Install
                    run: npm install
                -   name: Build
                    run: npm run build
                -   name: Sync
                    run: npx cap sync android

                -   name: Setup JDK
                    uses: actions/setup-java@v4
                    with:
                        java-version: '17'
                        distribution: 'zulu'

                -   name: Build APK
                    run: cd android && ./gradlew assembleDebug

                -   name: Upload APK
                    uses: actions/upload-artifact@v4
                    with:
                        name: todo.apk
                        path: android/app/build/outputs/apk/debug/app-debug.apk
                        
            
    